---
# this assumes logsearch/bosh-silo is the director
name: "sanity-test"
director_uuid: <%= `bosh status | grep UUID | awk '{ print $2 }'` %>

releases:
  - name: "logsearch"
    version: "latest"

update:
  canaries: 1
  canary_watch_time: 30000
  update_watch_time: 30000
  max_in_flight: 2
  max_errors: 1

jobs:
  - name: api
    templates: 
      - release: "logsearch"
        name: "elasticsearch"
      - release: "logsearch"
        name: "api"
      - release: "logsearch"
        name: "kibana"
    instances: 1
    resource_pool: "silo-t2-medium-private"
    networks:
      - name: "silo-private"
    properties:
      elasticsearch:
        node:
          allow_data: false

  - name: "ingestor"
    templates:
    - release: "logsearch"
      name: "ingestor_lumberjack"
    - release: "logsearch"
      name: "ingestor_syslog"
    - release: "logsearch"
      name: "ingestor_relp"
    instances: 1
    resource_pool: "silo-t2-medium-private"
    networks:
      - name: "silo-private"

  - name: "queue"
    templates:
      - release: "logsearch"
        name: queue
    instances: 1
    resource_pool: "silo-t2-medium-private"
    networks:
      - name: "silo-private"

  - name: "log_parser"
    templates:
      - release: "logsearch"
        name: "log_parser"
    instances: 2
    resource_pool: "silo-t2-medium-private"
    networks:
      - name: "silo-private"

  - name: "elasticsearch"
    templates:
      - release: "logsearch"
        name: "elasticsearch"
    update:
      serial: true
    instances: 2
    resource_pool: "silo-t2-medium-private"
    networks:
      - name: "silo-private"
    persistent_disk: 1024
    properties:
      elasticsearch:
        node:
          allow_master: false

properties: 
  api:
    port: 80
  kibana:
   elasticsearch: "127.0.0.1:9200"
   port: 5601
  elasticsearch:
    host: "0.api.silo-private.sanity-test.bosh,0.elasticsearch.silo-private.sanity-test.bosh,1.elasticsearch.silo-private.sanity-test.bosh"
    cluster_name: "logsearch-sanity-test"
  redis:
    host: "0.queue.silo-private.sanity-test.bosh"
  logstash_ingestor:
    relp:
      port: 5515
    syslog:
      port: 5514
    syslog_tls:
      port: 443
      # ingestor-20241214a
      ssl_cert: |
          -----BEGIN CERTIFICATE-----
          MIICWjCCAcOgAwIBAgIJAN57Q1O2B6k0MA0GCSqGSIb3DQEBBQUAMG0xFTATBgNV
          BAoMDGxvZ3NlYXJjaC5pbzEeMBwGA1UECwwVQ2VydGlmaWNhdGUgQXV0aG9yaXR5
          MREwDwYDVQQDDAhpbmdlc3RvcjEhMB8GCSqGSIb3DQEJARYSbm9ib2R5QGV4YW1w
          bGUuY29tMB4XDTE0MTIxNzIyMDkyNloXDTI0MTIxNDIyMDkyNlowXDEVMBMGA1UE
          CgwMbG9nc2VhcmNoLmlvMQ0wCwYDVQQLDARURVNUMREwDwYDVQQDDAhpbmdlc3Rv
          cjEhMB8GCSqGSIb3DQEJARYSbm9ib2R5QGV4YW1wbGUuY29tMIGfMA0GCSqGSIb3
          DQEBAQUAA4GNADCBiQKBgQClKtJSXPwsPWPIhSFqPDcyQwvsIY/nF+vNjetX1xjC
          ATC6F6ZaKCcddF1JaomTiPR9+qVeNedGwvtcrCLyOYpqBWs6KuCq4dE/7QxEwova
          yLEQRGMvZW8OClpjY0PdrpX+ekqllD/7CTMYvabc3Kq0Q6WPZAGLo01YoW2KKr13
          GQIDAQABoxMwETAPBgNVHREECDAGhwQK9AIOMA0GCSqGSIb3DQEBBQUAA4GBAFLV
          Z59nPFO1+W407lDCm4tXV3RpUCt4drAqNp1xum6U9fkcgzU0ZhrfmVCqGdFGWxxM
          Jhe1iAbho/Jb85V9hB9txr2Uh5Xvr0r0faeJYqFF+NCc9G+PKiNVwbId0rH2bfwr
          YLxYAgzDDozZ1bUSUQKbkiX8jSQHB63MPZXSAMWb
          -----END CERTIFICATE-----
      ssl_key: |
          -----BEGIN RSA PRIVATE KEY-----
          MIICXAIBAAKBgQClKtJSXPwsPWPIhSFqPDcyQwvsIY/nF+vNjetX1xjCATC6F6Za
          KCcddF1JaomTiPR9+qVeNedGwvtcrCLyOYpqBWs6KuCq4dE/7QxEwovayLEQRGMv
          ZW8OClpjY0PdrpX+ekqllD/7CTMYvabc3Kq0Q6WPZAGLo01YoW2KKr13GQIDAQAB
          AoGAHX57Flgic+f2hJ05bVYZaTFN1Lndj5/W7Nr19rajZil+QQzuGNVovrrD2dNb
          g+wF9OUoWJ15kkpJRrA6gVTDIYgZwoWjpo1X6NKfiMGbtITSePfwB17egeaVvoKW
          nxfhd5absxOAC13hXNGEIyklzBMzyikTbrlemeo07gLq+H0CQQDWzxVTIXesjQ2S
          Um9vvsUdlxqU5AjvsVPDZP3/d3NYF0ZALyyeqg1mE+pc4gEXw3T5Q5IMyxxFZjqQ
          m2mpuZzDAkEAxNbXko2mSopYZ5/LR6KJFvze8t70b0TUvlvPvM3M6pMeViqSrfyt
          QvHMNPRxbgoniNwm7W9x6Jp2UAUzH2kO8wJBAJc3KkTeH3fpx+8EdwwMGIkPERhV
          OvE5PMUlOCT5usn9gGe4jcmX3lzIkkgWlTxcTOEYLx0wclNsdrfLn+NqFa8CQByU
          xYB2KOsx41xIi4+/PgCkfwrs7LkrWWi6lBNqHpMBAaqpS9sPkWjjCy+1PrMnrk3l
          CZH4WKXZp8w+tQmei5kCQCxQ6Se1d1fSYQlLsCoTKmbcOjFoT5joj1nMIwSwn/Sy
          eevXlJLkedUMlEntH3b+dQjaRSWwWWtjzxY/Ou0CLKI=
          -----END RSA PRIVATE KEY-----
    lumberjack:
      # ingestor-20241214a
      ssl_certificate: |
          -----BEGIN CERTIFICATE-----
          MIICWjCCAcOgAwIBAgIJAN57Q1O2B6k0MA0GCSqGSIb3DQEBBQUAMG0xFTATBgNV
          BAoMDGxvZ3NlYXJjaC5pbzEeMBwGA1UECwwVQ2VydGlmaWNhdGUgQXV0aG9yaXR5
          MREwDwYDVQQDDAhpbmdlc3RvcjEhMB8GCSqGSIb3DQEJARYSbm9ib2R5QGV4YW1w
          bGUuY29tMB4XDTE0MTIxNzIyMDkyNloXDTI0MTIxNDIyMDkyNlowXDEVMBMGA1UE
          CgwMbG9nc2VhcmNoLmlvMQ0wCwYDVQQLDARURVNUMREwDwYDVQQDDAhpbmdlc3Rv
          cjEhMB8GCSqGSIb3DQEJARYSbm9ib2R5QGV4YW1wbGUuY29tMIGfMA0GCSqGSIb3
          DQEBAQUAA4GNADCBiQKBgQClKtJSXPwsPWPIhSFqPDcyQwvsIY/nF+vNjetX1xjC
          ATC6F6ZaKCcddF1JaomTiPR9+qVeNedGwvtcrCLyOYpqBWs6KuCq4dE/7QxEwova
          yLEQRGMvZW8OClpjY0PdrpX+ekqllD/7CTMYvabc3Kq0Q6WPZAGLo01YoW2KKr13
          GQIDAQABoxMwETAPBgNVHREECDAGhwQK9AIOMA0GCSqGSIb3DQEBBQUAA4GBAFLV
          Z59nPFO1+W407lDCm4tXV3RpUCt4drAqNp1xum6U9fkcgzU0ZhrfmVCqGdFGWxxM
          Jhe1iAbho/Jb85V9hB9txr2Uh5Xvr0r0faeJYqFF+NCc9G+PKiNVwbId0rH2bfwr
          YLxYAgzDDozZ1bUSUQKbkiX8jSQHB63MPZXSAMWb
          -----END CERTIFICATE-----
      ssl_key: |
          -----BEGIN RSA PRIVATE KEY-----
          MIICXAIBAAKBgQClKtJSXPwsPWPIhSFqPDcyQwvsIY/nF+vNjetX1xjCATC6F6Za
          KCcddF1JaomTiPR9+qVeNedGwvtcrCLyOYpqBWs6KuCq4dE/7QxEwovayLEQRGMv
          ZW8OClpjY0PdrpX+ekqllD/7CTMYvabc3Kq0Q6WPZAGLo01YoW2KKr13GQIDAQAB
          AoGAHX57Flgic+f2hJ05bVYZaTFN1Lndj5/W7Nr19rajZil+QQzuGNVovrrD2dNb
          g+wF9OUoWJ15kkpJRrA6gVTDIYgZwoWjpo1X6NKfiMGbtITSePfwB17egeaVvoKW
          nxfhd5absxOAC13hXNGEIyklzBMzyikTbrlemeo07gLq+H0CQQDWzxVTIXesjQ2S
          Um9vvsUdlxqU5AjvsVPDZP3/d3NYF0ZALyyeqg1mE+pc4gEXw3T5Q5IMyxxFZjqQ
          m2mpuZzDAkEAxNbXko2mSopYZ5/LR6KJFvze8t70b0TUvlvPvM3M6pMeViqSrfyt
          QvHMNPRxbgoniNwm7W9x6Jp2UAUzH2kO8wJBAJc3KkTeH3fpx+8EdwwMGIkPERhV
          OvE5PMUlOCT5usn9gGe4jcmX3lzIkkgWlTxcTOEYLx0wclNsdrfLn+NqFa8CQByU
          xYB2KOsx41xIi4+/PgCkfwrs7LkrWWi6lBNqHpMBAaqpS9sPkWjjCy+1PrMnrk3l
          CZH4WKXZp8w+tQmei5kCQCxQ6Se1d1fSYQlLsCoTKmbcOjFoT5joj1nMIwSwn/Sy
          eevXlJLkedUMlEntH3b+dQjaRSWwWWtjzxY/Ou0CLKI=
          -----END RSA PRIVATE KEY-----

apply_spec:
  properties:
    ntp:
      - 0.pool.ntp.org
      - 1.pool.ntp.org

resource_pools:
  # note this is not actually used; it just keeps the bosh-deployment-resource happy
  - name: unused
    network: concourse
    cloud_properties:
      instance_type: t2.micro
      availability_zone: us-east-1a
    stemcell:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
      version: latest
